version: '3.8'
services:
  appflowy_ai:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ".env"
    environment:
      FLASK_DEBUG: "false"
      FLASK_SKIP_DOTENV: "true"
