#!/usr/bin/env bash

set -o errexit
set -o pipefail

function lint {
  # Lint Python code
  flake8 "${@}"
}

function format:imports {
  # Sort Python imports
  isort . "${@}"
}

function format {
  # Format Python code
  black . "${@}"
}

function quality {
  # Perform all code quality commands together
  format:imports "${@}"
  format "${@}"
  lint "${@}"
}

function test {
  # Run test suite
  pytest ./tests
}

function pip3:outdated {
  # List any installed packages that are outdated
  pip3 list --outdated
}

function install_requirements {
  pip3 install -r requirements.txt
}

function start_server {
  flask run
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
