#!/usr/bin/env bash

set -o errexit
set -o pipefail

function lint {
  # Lint Python code
  flake8 "${@}"
}

function format:imports {
  # Sort Python imports
  isort . "${@}"
}

function format {
  # Format Python code
  black . "${@}"
}

function gen_requirements {
  pip freeze > requirements.txt
}

function install_requirements {
  pip install -r requirements.txt
}

function quality {
  # Perform all code quality commands together
  format:imports
  format
  lint
}